#pragma once

#include "keysym.h"

#include <stdint.h>

/* Consumer Page (0x0C) */
#define KS_MUTE KS_AUDIO_MUTE
#define KS_VOLU KS_AUDIO_VOL_UP
#define KS_VOLD KS_AUDIO_VOL_DOWN
#define KS_MNXT KS_MEDIA_NEXT_TRACK
#define KS_MPRV KS_MEDIA_PREV_TRACK
#define KS_MSTP KS_MEDIA_STOP
#define KS_MPLY KS_MEDIA_PLAY_PAUSE
#define KS_MSEL KS_MEDIA_SELECT
#define KS_EJCT KS_MEDIA_EJECT
#define KS_CALC KS_CALCULATOR
#define KS_MYCM KS_MY_COMPUTER
#define KS_WSCH KS_WWW_SEARCH
#define KS_WHOM KS_WWW_HOME
#define KS_WBAK KS_WWW_BACK
#define KS_WFWD KS_WWW_FORWARD
#define KS_WSTP KS_WWW_STOP
#define KS_WREF KS_WWW_REFRESH
#define KS_WFAV KS_WWW_FAVORITES
#define KS_MFFD KS_MEDIA_FAST_FORWARD
#define KS_MRWD KS_MEDIA_REWIND
#define KS_BRIU KS_BRIGHTNESS_UP
#define KS_BRID KS_BRIGHTNESS_DOWN

enum keysym_consumer {
	KS_AUDIO_MUTE = SPECIAL(0, S_CONSUMER),
	KS_AUDIO_VOL_UP,
	KS_AUDIO_VOL_DOWN,
	KS_MEDIA_NEXT_TRACK,
	KS_MEDIA_PREV_TRACK,
	KS_MEDIA_STOP,
	KS_MEDIA_PLAY_PAUSE,
	KS_MEDIA_SELECT,
	KS_MEDIA_EJECT,
	KS_MAIL,
	KS_CALCULATOR,
	KS_MY_COMPUTER,
	KS_WWW_SEARCH,
	KS_WWW_HOME,
	KS_WWW_BACK,
	KS_WWW_FORWARD,
	KS_WWW_STOP,
	KS_WWW_REFRESH,
	KS_WWW_FAVORITES,
	KS_MEDIA_FAST_FORWARD,
	KS_MEDIA_REWIND,
	KS_BRIGHTNESS_UP,
	KS_BRIGHTNESS_DOWN
};

uint16_t keysym_to_consumer(uint32_t keysym);
